### ISSUE TITLE
Job Config Runner

### ISSUE THREAD

**Issue by zkldi** [TNG-dev/tachi-server#250]
We need something to run a jobconf file defined inside `src/lib/jobs`.

This is part of a much larger CD project, and implementation is pretty much down to ereti.

As such, I'll stay hands-off on this issue, just let me know what kind of format you expect the jobconf to be in.

**Comment by ereti** [comment]
(Option 2b would be to not dockerize the job stuff and just run it on the host machine. Honestly, I think that's an ok solution (and has the added bonus of not having to worry about job persistence/missed job runs during server restarts/deployments/maintenance, but it would still require the aforementioned moving of the job code.)

**Comment by zkldi** [comment]
Fixed and implemented in #366.
