### ISSUE TITLE
Emails need some more content / Emails are getting spam filtered by gmail and other providers.

### ISSUE THREAD

**Issue by ereti** [TNG-dev/tachi-server#460]
Emails are still going to spam for 'looking similar to other spam'. They need padding out/having assets added to them to distinguish them in the eyes of spam filters.

**Comment by zkldi** [comment]
Enough people have marked these emails as not spam, gmail is now letting them slide. Going to downgrade this to low priority.

**Comment by zkldi** [comment]
Meh. Looks like emails are definitely going through now (or ending up in spam). Closing this.
