### ISSUE TITLE
INFINITAS Fervidex /class/submit data is always sending cleared: false.

### ISSUE THREAD

**Issue by hibikidesu** [TNG-dev/tachi-server#477]
After completing a dan course, fer sends `class/submit` to the server and it accepts it without any errors. All scores for the course get submitted and work as usual but dan does not update on the profile.

**Comment by zkldi** [comment]
Fervidex is sending `cleared: false` no matter what from infinitas, looks like some sort of bug not on our end. I'll leave this open just in case.

**Comment by zkldi** [comment]
Fixed by aixxe in a Fervidex update.
