### ISSUE TITLE
USC Converts are in a terrible state

### ISSUE THREAD

**Issue by zkldi** [TNG-dev/tachi-server#612]
Oh Boy, this might be worse than any other data issue we've had to deal with so far.

# Overview
Charts in USC are identified by their sha1sum. This is great for avoiding stupid things like songtitle matching (which is a terrible idea).
BMS uses this with md5/sha2, and it works great over there. The difference - however - between bms and usc in this regard is that USC charts are mostly converted by hand from SDVX.

It's also worth noting that 10 minutes ago I was told that almost every single convert has a noticeable error, such as missing notes, notes on completely wrong snaps, or holds that end way too early. This is the crux of the issue -- **so many people are silently playing on broken or different versions of the 'same' chart**.

Since we use the sha1sum to identify charts, all of these charts are regarded as different charts. This means the IR inevitably gets flooded with garbage, and we have to deal with it all. There isn't a nice fix for this at the moment.

I'm thinking of standardising on the oniichan converts, since those seem to be what most players use. However, there's no telling whether they'll silently back-update charts, or some garbage like that.

Standardising doesn't help much either, since thousands of players still have incorrect converts on their harddrive, and asking them to update to different versions is going to be a massive pain. I think we are actually just kind of screwed here.

# Unscrewing
One of the hacks we could use is rejecting new charts on the IR *if* and only *if* they have the same song title as an official already on the IR, and the same difficulty. This would reject spam small diffs to the IR, and ultimately reduce the amount of cleaning that has to be done.

I'll also need to append the sha1sums from oniichan at some point. That'll be fun.

**Comment by cg505** [comment]
> rejecting new charts on the IR _if_ and only _if_ they have the same song title as an official already on the IR, and the same difficulty

may want to add effector here, since there are some songs that have multiple customs created by different people

**Comment by zkldi** [comment]
Oh right, I don't even store effector at the moment I don't think. I should probably go store that.

**Comment by zkldi** [comment]
tachi-common just got bumped to support this.

It looks like we'll need to do a complete database migration on USC though. Mayaswell get this done as soon as possible to cause the least damage.

**Comment by zkldi** [comment]
Alright. I've pushed a hotfix to disable ASR (Automatic Score Reification -- automatically adding charts to the database if not present), since this can't be trusted the same way BMS can.

We're going to go back to using the whitelist defined in Tachi-Database-Seeds. We have full control over it, and can handle it very easily. It's just going to have to be that way.

We can add sets of customs (and tables, if anyone makes those), but for the time being supporting ALL customs on USC is a fools errand.

This change will have to be implemented in tachi-database-seeds, but it's still a bit of a server problem.

**Comment by zkldi** [comment]
We're maintaining our own downloads now. This mostly solves the problem.
