### ISSUE TITLE
Change `class` updates in BATCH MANUAL to use string enums

### ISSUE THREAD

**Issue by zkldi** [TNG-dev/tachi-server#684]
Instead of integers -- which are undoubtedly going to be a source of bugs.

**Comment by cg505** [comment]
is the plan to change all instances of class reference to enums, or just for batch manual?

**Comment by zkldi** [comment]
Just for batch-manual input -- it should be a string.

The internal representation should be an int because classes are by definition sorted.

This is consistent with things like `lamp`, where it gets churned into `lampIndex`.

**Comment by cg505** [comment]
other areas of the API (e.g. UGPT info) return the index, does that still seem ok?

**Comment by zkldi** [comment]
yeah this is fine. Returning integers is okay, parsing integers is a footgun.
