### ISSUE TITLE
Export All Scores Endpoint

### ISSUE THREAD

**Issue by zkldi** [TNG-dev/tachi-server#685]
Some users might want to export all of their scores to do other things with it. Given that these files may be huge, this endpoint needs to be significantly rate limited, and maybe even tar.gz'd, stored, and emailed to the user.

We'll just export everything as is -- just a raw dump of their scores collection. More advanced things (export all PBs endpoint) already exists.

**Comment by cg505** [comment]
one option: a very simple paginated API for all scores
another option: a request button that queues a job and emails you the result (which is a zip of batch manuals for all your scores or something) along the lines of how most companies do GDPR takeouts
