### ISSUE TITLE
ITG Stamina Support

### ISSUE THREAD

**Issue by zkldi** [TNG-dev/tachi-server#717]
I've been playing it too much and it'll take too long to write my own client (even though that's 100% what needs to be done.)

This is a stopgap solution but I think it'll be fun. We'll fork the groovestats launcher and push tachi into it, then we'll roll.

I only intend to support ITG Stamina at the moment -- they'll be separate GPTs (ITG Stamina (Single), maybe?). Then I'm just going to add support for all the packs I care about. That's ECS8 -> ECS10.5 and SRPG3-5. That's enough content for everyone, right? I don't really know. Our tables/folders solution should end up being fairly elegant though.

I wonder what kind of data we can pull from the client?

For scoring, I'm torn on what to actually use. EX Score is probably better for Stam FA nerds? I don't really know or care that much, since I think I'm personally only going to be focused on lamps.

We'll use a profile rating of like, avg best 20 blocks. Seems good to me. We can also have server announcements for when someone raises their block level.

This support will effectively just be for my personal usage, I don't intend for this to be a groovestats replacement or anything (Those guys are working on a full site rewrite, so god knows what I'm intruding on.)

**Comment by cg505** [comment]
Why separate GPTs?

**Comment by zkldi** [comment]
Despite having almost identical gameplay, the goals of ITG Stamina differ massively from ITG FA -- What a stamina player wants to see on their page is radically different to what they would like to see about their FA scores.

The same applies to chart ratings, leaderboards, lamps, and more. It makes sense to me -- personally -- to split the two?

There's some overlap (ITL's stamina picks, for example) but that can be handled later.

**Comment by cg505** [comment]
Well, it doesn't matter that much at this phase, but my take:
Pros of splitting:
- Captures the fact that they are quite different ways of playing the game
- Block ratings use different scales
  - theoretically true, but there is not much overlap and players are used to navigating this confusion
- players care about different metrics (e.g. money vs ex score, profile ratings like highest block rating pass/32m bpm pass)
  - feels like a similar situation to iidx BPI vs ktLampRating, users can select what they want
  - things like highest block rating or BPM will naturally come from stamina charts anyway
- allows better flexibility about which timing windows are allowed (e.g. FA+ for FA play, required boys on for stamina play)
Cons of splitting:
- People (especially noobs) often don't think too much of the distinction and players may switch back and forth within the same session or even credit
  - Technically other SP/DP games can have this issue
- You have to categorize everything into either stamina or tech, which is harder than it sounds. Also, stamtech exists
  - The same song can have multiple diffs which are either stamina- or FA-focused

Actually after writing everything down I kind of agree with you but it just feels weird lol

**Comment by cg505** [comment]
probably good to get an actual ITG player's take on this though LMAO

**Comment by zkldi** [comment]
> Well, it doesn't matter that much at this phase, but my take: Pros of splitting:
> 
>     * Captures the fact that they are quite different ways of playing the game
> 
>     * Block ratings use different scales
>       
>       * theoretically true, but there is not much overlap and players are used to navigating this confusion

We can use table-esque implementations to separate the "blocks". It's possible to push them both into the same thing.

>     * players care about different metrics (e.g. money vs ex score, profile ratings like highest block rating pass/32m bpm pass)
>       
>       * feels like a similar situation to iidx BPI vs ktLampRating, users can select what they want
>       * things like highest block rating or BPM will naturally come from stamina charts anyway

Yup, the existing switchy options on the site would let people do this. 

>     * allows better flexibility about which timing windows are allowed (e.g. FA+ for FA play, required boys on for stamina play)

This is a major part -- stamina players play with EX Score and (generally) boys on -- We can copy the srpg ruling that scores on charts rated about 17 *require* the boys to be on, or we can just mandate them to be on to begin with. I'm going to dm Archi about this for his opinion.

> Cons of splitting:
> 
>     * People (especially noobs) often don't think too much of the distinction and players may switch back and forth within the same session or even credit
>       
>       * Technically other SP/DP games can have this issue

Support for ITG Stamina is only really intended as a temporary stopgap while I play the game more. I intend to eventually make my own 4Panel client that won't have any of the previous problems.

>     * You have to categorize everything into either stamina or tech, which is harder than it sounds. Also, stamtech exists
>       
>       * The same song can have multiple diffs which are either stamina- or FA-focused

This part is probably the messiest -- that said, I don't care enough to actually ever write support for ITG Tech at the moment. Everything supported will be Stamina.
